keys:
  - &admin_nase age1ku90ahpfvzstfzuu4x5fagp5t25mmjt0pj9jasmvcrhu60hn4f8qkjl7ae
  - &system_ashes age1t2ysmpkapnajmu8qspp9h3369n354cdzp69a08xjj390q7h5vgcq4d4w8s
  - &system_driftwood age17enzqfxrydaasa0qh33vrkml6zfksww7vltln54dcczffd9g6dxqgdy6e2
  - &system_forest age13554wqldlmt7jnjx5mjw9l246zmgmus4lc6r0vyt5sag2m2tjdeq2rsdft
  - &system_timber 78f0356e09cbc091b41556b39234f0685cb96375
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *admin_nase
      - *system_ashes
      - *system_driftwood
      - *system_forest
    - pgp:
      - *system_timber