on: [push]

jobs:
  check_flake:
    runs-on: native
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
      
      - name: verify WD
        run: nix flake show

      - name: check flake
        run: nix flake check