on: [push]

jobs:
  check_flake:
    runs-on: native
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show flake outputs
        run: nix flake show

      - name: Show flake metadata
        run: nix flake metadata
      
      - name: Check flake evaluation
        run: nix flake check --log-format raw -vv