name: Print information about opened PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronized]

jobs:
  print_pr_info:
    runs-on: codeberg-small
    container:
      image: nixos/nix:2.26.1
      env:
        NIX_CONFIG: experimental-features = "nix-command flakes"
    steps:
      - name: Check flake evaluation
        run: nix flake check