on:
  pull_request:
    types: [opened, closed]

jobs:
  print_pr_info:
    runs-on: native
    steps:
      - name: hopefully print event info
        run: echo ${{ toJSON(github.event.pull_request) }}