name: Ensure valid configuration

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronized]

jobs:
  validate:
    runs-on: codeberg-small
    container:
      image: nixos/nix:2.26.1
      env:
        NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - name: Check flake evaluation
        run: |
          git clone $GITHUB_HEAD_REF .
          nix flake check