name: Ensure valid configuration

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronized]

jobs:
  validate:
    runs-on: codeberg-small
    container:
      image: nixos/nix:2.26.1
      env:
        NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - name: Check flake evaluation
        run: |
          echo $GITHUB_SHA
          echo ${{ github.event.pull_request.head.clone_url }}
          git clone ${{ github.event.pull_request.head.clone_url }} .
          nix flake check