name: Print information about opened PR

on:
  pull_request:
    types: [opened, synchronized]

jobs:
  print_pr_info:
    runs-on: native
    steps:
      - name: print event info
        shell: bash
        env:
          PR: ${{ toJSON(github.event.pull_request) }}
        run: |
          echo $PR