name: Ensure valid configuration

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronized ]
    branches: [ main ]

jobs:
  validate:
    runs-on: codeberg-small
    container:
      image: nixos/nix:2.26.1
      env:
        NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - name: Checkout repo
        run: |
          git clone https://codeberg.org/nklsfrt/nixos/ .
          git checkout $GITHUB_SHA
      - name: Check flake evaluation
        run: nix flake check