name: Ensure valid configuration

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronized ]
    branches: [ main ]

jobs:
  validate:
    runs-on: codeberg-small
    container:
      image: nixos/nix:2.26.1
      env:
        NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - name: Check flake evaluation
        run: |
          echo "$${{ github.event.pull_request.clone_url }}?ref=$GITHUB_SHA"
          nix flake check $${{ github.event.pull_request.clone_url }}?ref=$GITHUB_SHA