name: Ensure valid configuration

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronized ]
    branches: [ main ]

jobs:
  validate:
    runs-on: codeberg-small
    container:
      image: nixos/nix:2.26.1
      env:
        NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - name: Check flake evaluation
        run: nix flake check git+${{ github.event.repository.html_url }}?rev=$GITHUB_SHA