on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '20 4 * * 6'

jobs:
  update_flake_lock:
    runs-on: native
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update flake.lock
        run: nix flake update

      - name: Check flake evaluation
        run: nix flake check

      - name: Commit updated flake.lock
        if: success()
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@noreply.codeberg.org'
          git checkout -b updated-flake
          git add flake.lock
          git commit -m 'update flake.lock'
          git push origin updated-flake

      - name: Create Pull Request
        uses: https://github.com/peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update flake.lock
          branch: updated-flake
          title: Update flake.lock.
          body: This PR updates the flake.lock file with the latest versions.
          base: main
