on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '20 4 * * 6'

jobs:
  update_flake_lock:
    runs-on: native
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update flake.lock
        run: nix flake update

      - name: Check flake evaluation
        run: nix flake check

      - name: Commit updated flake.lock
        if: success()
        run: |
          git config --global user.name 'forgejo-actions'
          git config --global user.email 'actions@noreply.forgejo.org'
          git checkout -b updated-flake
          git add flake.lock
          git commit -m 'Update flake.lock'
          git push origin updated-flake