name: Update the flake.lock file

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * 6'

jobs:
  update_flake_lock:
    runs-on: native
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update flake.lock
        run: |
          git config user.name nklsfrt
          git config user.email nklsfrt@posteo.de
          git checkout -b updated-flake
          nix flake update --commit-lock-file

      # - name: Check flake evaluation
      #   run: nix flake check

      - name: Create a pull request
        run: |
          curl -H "Authorization: token ${RUNNER_PAT}" \
          --json '{"head": "updated-flake", "base": "main", "title": "[Scheduled] Updated flake.lock"}' \
          "https://codeberg.org/api/v1/repos/nklsfrt/nixos/pulls"
        env:
          RUNNER_PAT: ${{ secrets.RUNNER_PAT }}

      - name: Confirm success
        if: success()
        run: echo "Evaluation was successful!"
