name: Update the flake.lock file

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * 6'

jobs:
  update_flake_lock:
    runs-on: native
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update flake.lock
        run: |
          git config user.name "Niklas Furtwängler"
          git config user.email "furtwaengler@posteo.de"
          git checkout -b updated-flake
          nix flake update --commit-lock-file

      - name: Create a pull request
        if: success()
        run: |
          git push --force --set-upstream origin updated-flake
          curl -H "Authorization: token ${RUNNER_PAT}" \
          --json '{"head": "updated-flake", "base": "main", "title": "[Scheduled] Updated flake.lock"}' \
          "https://codeberg.org/api/v1/repos/nklsfrt/nixos/pulls"
        env:
          RUNNER_PAT: ${{ secrets.RUNNER_PAT }}
