name: Update flake

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update_flake_lock:
    runs-on: native
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show flake metadata
        run: nix flake metadata

      - name: Update flake.lock
        run: nix flake update

      - name: Show flake metadata
        run: nix flake metadata

      - name: Check flake evaluation
        run: nix flake check --log-format raw -vv

      - name: Commit
        if: success()
        run: |
          git config --global user.name 'forgejo-actions'
          git config --global user.email 'actions@noreply.forgejo.org'
          git checkout -b updated-flake
          git add flake.lock
          git commit -m 'Update flake.lock'
          git push origin updated-flake