on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '20 4 * * 6'

jobs:
  update_flake_lock:
    runs-on: native
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: updated-flake

      - name: Rebase from main
        run: git rebase origin main

      - name: Update flake.lock
        run: nix flake update

      - name: Stage flake.lock
        run: git add flake.lock

      - name: Check flake evaluation
        run: nix flake check

      - name: Commit updated flake.lock
        if: success()
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@noreply.codeberg.org'
          git add flake.lock
          git commit -m 'Update flake.lock'
          git push origin updated-flake