name: Update the flake.lock file

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * 6'

jobs:
  update_flake_lock:
    runs-on: codeberg-tiny
    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install nix package manager
        uses: https://github.com/DeterminateSystems/nix-installer-action@v16

      - name: Update flake.lock
        run: |
          git config user.name "nklsfrt"
          git config user.email "nklsfrt@noreply.codeberg.org"
          git checkout -b updated-flake
          nix flake update --commit-lock-file

      - name: Create a pull request
        if: success()
        run: |
          git push --set-upstream origin updated-flake
          curl -H "Authorization: token ${RUNNER_PAT}" \
          -H "Content-Type: application/json" \
          -H "Accept: application/json" \
          --data '{"head": "updated-flake", "base": "main", "title": "[Scheduled] Updated flake.lock"}' \
          "https://codeberg.org/api/v1/repos/nklsfrt/nixos/pulls"
        env:
          RUNNER_PAT: ${{ secrets.RUNNER_PAT }}
